### ISSUE TITLE
Feature Request: No Crash Dialogue

### ISSUE THREAD

**Issue by davechurchill** [blole/injectory#10]
Hello! We are going to be using Injectory for the Starcraft AI Tournament Manager project as a replacement for Chaoslauncher, which cannot be run without a GUI, and I have a feature request that you may consider for your project.

Currently, when we use Injectory to inject a BWAPI bot DLL into Starcraft, if that bot crashes, an application error dialogue pops up which does not go away after the process has terminated. Since that error message is part of a system service, it cannot easily be closed automatically by our software.

We found that you can use the following code (on windows) to disable error message dialogues:

#ifdef WIN32
DWORD dwMode = SetErrorMode(SEM_NOGPFAULTERRORBOX);
SetErrorMode(dwMode | SEM_NOGPFAULTERRORBOX);
#endif

My feature request for Injectory would be to add this code as a command-line flag so that you can disable error message dialogues from appearing if you want to. We have tested it with your code and it works simply by inserting that code snippet at the beginning of main()

**Comment by blole** [comment]
Cool 😄 I'll have a look at it.

**Comment by blole** [comment]
Alright, try if release [6.0.0](https://github.com/blole/injectory/releases/tag/6.0.0) works with the additional command line arguments
`--set-flags SEM_NOGPFAULTERRORBOX`, otherwise I think I'll have to start writing test applications (heh).

Also, was there any particular reason to do the `#ifdef WIN32`?

**Comment by davechurchill** [comment]
I think because it is a windows specific flag :) will test it soon

**Comment by richard-kelly** [comment]
The new release with the SEM_NOGPFAULTERRORBOX flag is working for us. No crash dialogues. (I'm working with @davechurchill on the Tournament Manager) Thanks!
